name: FoxESS Control
description: >-
  Installs the FoxESS Control custom integration into Home Assistant.
  Manages battery charge/discharge schedules via the FoxESS Cloud API.
version: 0.13.2-beta.3
slug: foxess_control
url: https://github.com/nicois/foxess-control
image: ghcr.io/nicois/foxess-control-{arch}
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: once
boot: auto
map:
  - config:rw
apparmor: true
options: {}
schema: {}
